CREATE TABLE stock_movement
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference_id VARCHAR(255),
    timestamp    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stock_movement PRIMARY KEY (id)
);

CREATE TABLE stock_movement_line
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_id          BIGINT                                  NOT NULL,
    quantity          INTEGER,
    source_location   VARCHAR(255),
    target_location   VARCHAR(255),
    stock_movement_id BIGINT,
    CONSTRAINT pk_stock_movement_line PRIMARY KEY (id)
);

ALTER TABLE stock_movement_line
    ADD CONSTRAINT FK_STOCK_MOVEMENT_LINE_ON_BATCH FOREIGN KEY (batch_id) REFERENCES batch_inventory (batch_id);

ALTER TABLE stock_movement_line
    ADD CONSTRAINT FK_STOCK_MOVEMENT_LINE_ON_STOCK_MOVEMENT
        FOREIGN KEY (stock_movement_id) REFERENCES stock_movement (id);