SET search_path TO public;


CREATE TABLE batch_inventory
(
    batch_id                BIGINT NOT NULL,
    product_id              VARCHAR(255),
    purchase_invoice_no     BIGINT,
    manufacture_date        date,
    expiry_date             date,
    purchased_unit_quantity INTEGER,
    available_unit_quantity INTEGER,
    cost_per_unit           DECIMAL,
    retail_price            DECIMAL,
    discount                DECIMAL,
    batch_status            VARCHAR(255),
    date_received           date,
    CONSTRAINT pk_batch_inventory PRIMARY KEY (batch_id)
);

CREATE TABLE product
(
    product_id                    VARCHAR(50) NOT NULL,
    product_name                  VARCHAR(255),
    purchase_group_id             INTEGER,
    generic_name                  VARCHAR(255),
    description                   VARCHAR(255),
    product_model_no              VARCHAR(255),
    category                      VARCHAR(255),
    dosage_form                   VARCHAR(255),
    selling_unit                  VARCHAR(255),
    package_type                  VARCHAR(255),
    product_status                VARCHAR(255),
    reorder_limit_by_selling_unit INTEGER,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE product_retail_price
(
    price_id       BIGINT                      NOT NULL,
    product_id     VARCHAR(50)                 NOT NULL,
    created_by     VARCHAR(255)                NOT NULL,
    effective_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    retail_price   DECIMAL                     NOT NULL,
    CONSTRAINT pk_product_retailprice PRIMARY KEY (price_id)
);

CREATE TABLE purchase_group
(
    purchase_group_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    purchase_group_name         VARCHAR(255),
    purchase_group_address      VARCHAR(255),
    purchase_group_contact_name VARCHAR(255),
    purchase_group_phone_no     VARCHAR(255),
    purchase_group_fax_no       VARCHAR(255),
    purchase_group_email        VARCHAR(255),
    CONSTRAINT pk_purchase_group PRIMARY KEY (purchase_group_id)
);

CREATE TABLE purchase_invoice
(
    invoice_id         BIGINT NOT NULL,
    invoice_status     VARCHAR(255),
    invoice_date       TIMESTAMP WITHOUT TIME ZONE,
    invoice_no         VARCHAR(255),
    payment_type       VARCHAR(255),
    total_amount       DECIMAL,
    discount_amount    DECIMAL,
    net_amount         DECIMAL,
    purchase_no        BIGINT NOT NULL,
    supplier_id        BIGINT NOT NULL,
    purchase_order_ref VARCHAR(255),
    CONSTRAINT pk_purchase_invoice PRIMARY KEY (invoice_id)
);

CREATE TABLE purchase_line_item
(
    line_item_id        BIGINT NOT NULL,
    product_id          VARCHAR(255),
    quantity_by_package INTEGER,
    conversion_factor   INTEGER,
    discount_amount     DECIMAL,
    cost_per_unit       DECIMAL,
    total_cost          DECIMAL,
    manufacture_date    date,
    expiry_date         date,
    unit_price          DECIMAL,
    purchase_invoice    BIGINT,
    CONSTRAINT pk_purchase_line_item PRIMARY KEY (line_item_id)
);

CREATE TABLE supplier
(
    supplier_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supplier_name       VARCHAR(255),
    supplier_address    VARCHAR(255),
    supplier_contact_no VARCHAR(255),
    supplier_email      VARCHAR(255),
    outstanding_balance DECIMAL,
    credit_limit        DECIMAL,
    credit_period       INTEGER,
    purchase_group_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_supplier PRIMARY KEY (supplier_id)
);

ALTER TABLE product_retail_price
    ADD CONSTRAINT FK_PRODUCT_RETAILPRICE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE supplier
    ADD CONSTRAINT FK_SUPPLIER_ON_PURCHASE_GROUP FOREIGN KEY (purchase_group_id) REFERENCES purchase_group (purchase_group_id);