CREATE SEQUENCE invoice_id_seq
    START WITH 1
    INCREMENT BY 50
    MINVALUE 0
    NO MAXVALUE
    CYCLE;

CREATE SEQUENCE line_item_id_seq
    START WITH 1
    INCREMENT BY 50
    MINVALUE 0
    NO MAXVALUE
    CYCLE;

CREATE SEQUENCE batch_id_seq
    START WITH 1
    INCREMENT BY 50
    MINVALUE 0
    NO MAXVALUE
    CYCLE;

CREATE SEQUENCE retail_price_id_seq
    START WITH 1
    INCREMENT BY 50
    MINVALUE 0
    NO MAXVALUE
    CYCLE;