SET search_path TO public;

CREATE TABLE customer(
    customerId BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customerAddress VARCHAR(255),
    customerContactName VARCHAR(255),
    customerNicNo VARCHAR(255),
    customerBrcNo VARCHAR(255),
    customerEmail VARCHAR(255),
    customerGroup VARCHAR(255),
    customerPhoneNo Integer,
    registeredDate LocalDate,
    creditLimit Double,
    creditPeriodInDays Integer,
    outstandingBalance Double,
    CONSTRAINT pk_customer PRIMARY KEY (customerId)

);
CREATE TABLE customer_group(
    customerGroupId BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customerGroupName VARCHAR(255),
    assigndSalesRep VARCHAR(255),
    description VARCHAR(255),
    customerIds Integer,
    CONSTRAINT pk_customerGroup PRIMARY KEY (customerGroupId)

);
ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMER_GROUP FOREIGN KEY (customerGroupId) REFERENCES customerGroup (customerGroupId);
