CREATE TABLE inventory
(
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_id  BIGINT                                  NOT NULL,
    batch_id     BIGINT                                  NOT NULL,
    quantity     INTEGER,
    CONSTRAINT pk_inventory PRIMARY KEY (inventory_id)
);

CREATE TABLE inventory_location
(
    location_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_type      VARCHAR(255),
    location_name      VARCHAR(255),
    total_capacity     INTEGER,
    available_capacity INTEGER,
    CONSTRAINT pk_inventory_location PRIMARY KEY (location_id)
);

CREATE TABLE truck_inventory
(
    inventory_id BIGINT NOT NULL,
    CONSTRAINT pk_truckinventory PRIMARY KEY (inventory_id)
);

CREATE TABLE warehouse_inventory
(
    inventory_id       BIGINT NOT NULL,
    warehouse_location VARCHAR(255),
    CONSTRAINT pk_warehouseinventory PRIMARY KEY (inventory_id)
);

ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_BATCH FOREIGN KEY (batch_id) REFERENCES batch_inventory (batch_id);

ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_LOCATION FOREIGN KEY (location_id) REFERENCES inventory_location (location_id);

ALTER TABLE truck_inventory
    ADD CONSTRAINT FK_TRUCKINVENTORY_ON_INVENTORY FOREIGN KEY (inventory_id) REFERENCES inventory (inventory_id);

ALTER TABLE warehouse_inventory
    ADD CONSTRAINT FK_WAREHOUSEINVENTORY_ON_INVENTORY FOREIGN KEY (inventory_id) REFERENCES inventory (inventory_id);