CREATE TABLE truck
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    truck_id            VARCHAR(255)                            NOT NULL,
    registration_number VARCHAR(255)                            NOT NULL,
    max_capacity        DOUBLE PRECISION                        NOT NULL,
    status              VARCHAR(255),
    date_added          TIMESTAMP WITHOUT TIME ZONE,
    assigned_repl_id    VARCHAR(255),
    current_capacity    DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_truck PRIMARY KEY (id)
);

ALTER TABLE truck
    ADD CONSTRAINT uc_truck_registrationnumber UNIQUE (registration_number);

ALTER TABLE truck
    ADD CONSTRAINT uc_truck_truckid UNIQUE (truck_id);

