SET search_path TO public;

CREATE TABLE customer_group (
                                customer_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                customer_group_name VARCHAR(255),
                                assigned_sales_rep VARCHAR(255),
                                descriptions VARCHAR(255),
                                CONSTRAINT pk_customer_group PRIMARY KEY (customer_group_id)
);

CREATE TABLE customer (
                          customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          customer_name VARCHAR(255),
                          customer_address VARCHAR(255),
                          customer_contact_name VARCHAR(255),
                          customer_nic_no VARCHAR(255),
                          customer_brc_no VARCHAR(255),
                          customer_email VARCHAR(255),
                          customer_group_id BIGINT,  -- Added to reference customer_group
                          customer_phone_no INTEGER,
                          registered_date DATE,  -- Fixed LocalDate -> DATE
                          credit_limit DOUBLE PRECISION, -- Fixed Double -> DOUBLE PRECISION
                          credit_period_in_days INTEGER,
                          outstanding_balance DOUBLE PRECISION, -- Fixed Double -> DOUBLE PRECISION
                          CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CUSTOMER_GROUP FOREIGN KEY (customer_group_id) REFERENCES customer_group (customer_group_id);