scrape_configs:
  - job_name: "PharmaPulse Metrices"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s # how often to scrape
    static_configs:
      - targets: ["host.docker.internal:8090"] # This is for demo purpose. During  production, change this to the production host address.